version: "3.8"

x-celery-env: &default-celery-env
  DJANGO_SETTINGS_MODULE: config.settings.local
  DB_NAME: webapp
  DB_HOST: db
  DATABASE_URL: postgres://admin:admin@db/webapp
  CELERY_BROKER_URL: redis://redis:6379/0


services:
  db:
    image: postgres:16-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  celery:
    build:
      context: ../
    command: celery -A webapp worker -l info
    volumes:
      - ../webapp:/app
    depends_on:
      - db
      - redis
    environment:
      <<: *default-celery-env

  celery-beat:
    build:
      context: ../
    command: celery -A webapp beat -l info
    volumes:
      - ../webapp:/app
    depends_on:
      - db
      - redis
    environment:
      <<: *default-celery-env
  flower:
    build:
      context: ../
    command: celery -A tasks flower
    ports:
      - "5555:5555"
    environment:
      <<: *default-celery-env
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery
      - redis

volumes:
  postgres_data: