global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "redis"
    static_configs:
      - targets: [ "redis_exporter:9121" ]
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:8000" ]