version: "3.8"



services:
  db:
    image: postgres:16-alpine3.20
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      REDIS_ADDR: redis://redis:6379
    ports:
      - "127.0.0.1:9121:9121"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./monitor/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    depends_on:
      - redis_exporter

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"




volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
