# Generated by Django 4.2.16 on 2024-10-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_add_initial_subjects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
